-- Migration 0019: task run history table.
--
-- Persists one row per task execution so users can see a timeline of
-- recent runs (success / failure / skipped) and plain-language failure
-- explanations without digging through server logs.
--
-- Design decisions:
--   - One row per logical execution (for cron/condition tasks) or per batch
--     run (not per sub-task) to keep volume manageable. Sub-task level
--     failures are already tracked in batch_subtasks.error_text.
--   - status: 'ok' | 'failed' | 'skipped'
--       ok      — trigger fired and data was written / action was taken
--       failed  — data-hub or LLM call failed after all retries
--       skipped — task was in cooldown / paused / data-hub unavailable
--   - summary_text: a short human-readable outcome (≤ 280 chars)
--   - error_text:   plain-language failure explanation (≤ 1000 chars);
--                   generated by the failure-explainer helper (no LLM)
--   - detail_json:  optional structured context (metric value, retry count…)
--   - finished_at:  NULL while the run is in progress (rare for cron tasks)
--
-- Index strategy:
--   - Primary lookup: recent runs for one task, owner-scoped
--     → idx_task_runs_owner_task_started (owner, task_id, started_at DESC)
--   - Age-based pruning (future): idx_task_runs_started (started_at)

CREATE TABLE IF NOT EXISTS task_runs (
  id          TEXT    NOT NULL PRIMARY KEY,    -- "run_<nanoid(12)>"
  owner       TEXT    NOT NULL DEFAULT 'anon',
  task_id     TEXT    NOT NULL,
  started_at  INTEGER NOT NULL DEFAULT (unixepoch()),
  finished_at INTEGER,                         -- NULL = still in progress
  status      TEXT    NOT NULL DEFAULT 'ok',   -- ok | failed | skipped
  summary_text TEXT,                           -- short human-readable outcome
  error_text   TEXT,                           -- plain-language failure reason
  detail_json  TEXT                            -- optional JSON context blob
);

-- Primary access pattern: list runs for a task, newest first (owner-scoped).
CREATE INDEX IF NOT EXISTS idx_task_runs_owner_task_started
  ON task_runs (owner, task_id, started_at DESC);

-- Secondary: age-based cleanup / global stats queries.
CREATE INDEX IF NOT EXISTS idx_task_runs_started
  ON task_runs (started_at DESC);

PRAGMA optimize;
